name: Rust Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}

    - name: Run tests
      run: cargo test --all --verbose
