name: Rust Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions/setup-toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test --all --verbose
